### ISSUE TITLE
Extend App\Http\Controllers\Controller instead Illuminate\Routing\Controller;

### ISSUE THREAD

**Issue by anandiamy** [laravolt/thunderclap#2]
Sometimes we want to use Policy in Controller 
https://laravel.com/docs/5.8/authorization#via-controller-helpers

If we use Illuminate\Routing\Controller, there is an exception
`Method authorize() does not exists`

So, I think we must use `App\Http\Controllers\Controller` instead `Illuminate\Routing\Controller`

![image](https://user-images.githubusercontent.com/8675936/58306901-3cc6da00-7e27-11e9-8146-5abf7f2b5823.png)

**Comment by uyab** [comment]
You just need to `use Illuminate\Foundation\Auth\Access\AuthorizesRequests;` in your controller.

```php
class FaqController extends Controller
{
    use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
}

```

**Comment by anandiamy** [comment]
Oh I see
